### ISSUE TITLE
Any pretrained model ?

### ISSUE THREAD

**Issue by leilegelei1** [catta202000/CMRNet#1]
Hi, can you share a pretrained model that help me do a quick verification on this approach?

**Comment by cattaneod** [comment]
Hi,
I just uploaded the model trained on the KITTI sequences 00, 03, 05, 06, 07, 08, 09.

**Comment by alliecc** [comment]
Hi @cattaneod, I found the tar file of trained models cannot be untar. Would you mind upload it again? Thanks!

**Comment by cattaneod** [comment]
you don't have to untar them.
just load them as they are with torch.load()

**Comment by alliecc** [comment]
It worked, thanks
