### ISSUE TITLE
Line of code seems incorrect

### ISSUE THREAD

**Issue by RaviBeagle** [catta202000/CMRNet#16]
Hello @cattaneod ,

What does these lines of code do:  https://github.com/cattaneod/CMRNet/blob/3359a2c85cbc7e270d499dd15b892f6bf058aac3/DatasetVisibilityKitti.py#L67

```
                if dir == test_sequence and split.startswith('test'):
                    self.all_files.append(os.path.join(dir, str(row['timestamp'])))
                elif (not dir == test_sequence) and split == 'train':
                    self.all_files.append(os.path.join(dir, str(row['timestamp'])))
```

I think something else was meant, but the all_files list is appended whether its test set or train set ?

Also in the same file I dont see  camera model self.model = CameraModel()
used anywhere in that file.

**Comment by cattaneod** [comment]
The lines are actually correct, it adds the sample to the all_files in two cases:
1 - split is test, and the current sequence is the test sequence
2 - split is train, and the current sequence is NOT the test sequence.

In short, it only adds samples from the test sequence if the split it test, or add sample from all sequences except for the test one if the split is train.
