### ISSUE TITLE
Some operations seem difficult to follow

### ISSUE THREAD

**Issue by RaviBeagle** [catta202000/CMRNet#17]
Hello @cattaneod 

I am checking out the code in evaluate_iterative_single_CALIB.py and some operations seem difficult to follow:

For example the line:
            pc_rotated = rotate_back(pc_rotated, R, T)

Is applying the error transform to the GT point cloud. 

But when I look at at another section of code:

  R = quat2mat(target_rot[0])
        T = tvector2mat(target_transl[0])
        RT1_inv = torch.mm(T, R)
        RT1 = RT1_inv.clone().inverse()

        rotated_point_cloud = rotate_forward(point_cloud, RT1)
        RTs = [RT1]

Its doing the same thing. Now the RT1 is inverted before calling rotate_forward. And within rotate_forward we have this code

    if isinstance(R, torch.Tensor):
        return rotate_points_torch(PC, R, T, **inverse=True**)
    else:
        return rotate_points(PC, R, T, **inverse=True**)

So its inverting again achieving same effect as the rotate_back ?

Thanks

**Comment by cattaneod** [comment]
rotate_back and rotate_forward are basically the same, but with the RT inverted.

In RTs I save the results:
RTs[0] is the initial estimation H_init
RTs[1] is H_init @ prediction1 (prediction of the first network)
RTs[2] is H_init @ prediction1 @ prediction2

and so on. Thus, the final RTs[-1] should be as close as possible to the identity matrix.

**Comment by RaviBeagle** [comment]
Yes. Thank you.
I do understand that rotate_back is meant to rotate the point cloud from estimated to real pose.
and rotate_forward from actual pose to erroneous pose. And only invert of RT is the difference between the two functions.

DataSetVisibility*.py
R = mathutils.Euler((rotx, roty, rotz), 'XYZ')
T = mathutils.Vector((transl_x, transl_y, transl_z))

        R, T = invert_pose(R, T)   ##  Invert Error Transform as 
        R, T = torch.tensor(R), torch.tensor(T)

But in in evaluate_*.py:

  R = mathutils.Quaternion(sample['rot_error'][idx])
            T = mathutils.Vector(sample['tr_error'][idx])
            print(pc_rotated.shape, R, T)
            pc_rotated = rotate_back(pc_rotated, R, T)

Here should we not use rotate_forward ? Or have got the understanding interchanged ?

**Comment by RaviBeagle** [comment]
I will keep the same conventions. So this is my code for now:

```
        max_angle = 10.0
        max_t = 2.0
        rotz = np.random.uniform(-max_angle, max_angle) * (3.141592 / 180.0)
        roty = np.random.uniform(-max_angle, max_angle) * (3.141592 / 180.0)
        rotx = np.random.uniform(-max_angle, max_angle) * (3.141592 / 180.0)
        transl_x = np.random.uniform(-max_t, max_t)
        transl_y = np.random.uniform(-max_t, max_t)
        transl_z = np.random.uniform(-max_t, min(max_t, 1.))

        R = mathutils.Euler((rotx, roty, rotz), 'XYZ')
        T = mathutils.Vector((transl_x, transl_y, transl_z))
        R_inv, T_inv = invert_pose(R, T)

        R = quat2mat(torch.tensor(R_inv,device='cuda'))
        T = tvector2mat(torch.tensor(T_inv,device='cuda'))

        RT1_inv = torch.mm(T, R)
        RT1 = RT1_inv.clone().inverse()
        rotated_point_cloud = rotate_forward(local_map, RT1)
        
        project_lidar_to_image(cam_params,rotated_point_cloud,rgb_image,True,"INPUT")
```
