### ISSUE TITLE
When i run kitti_maps.py, it displays "killed".

### ISSUE THREAD

**Issue by chenruijie1224** [catta202000/CMRNet#23]
When i run kitti_maps.py, it displays "killed", and fails to create .h5 files. How to solve this problem.

**Comment by cattaneod** [comment]
I need more information to help you. Does the folder where the .h5 files are created exist?

**Comment by fmaaf** [comment]
A computer with a larger memory can solve this problem.

**Comment by fmaaf** [comment]
or you can add the parameter like --end 2000, and next round, add --start 2000, to split the big folder into small ones.
