### ISSUE TITLE
Does CMRNet++ plan to open source?

### ISSUE THREAD

**Issue by tqltech** [catta202000/CMRNet#24]
Does CMRNet++ plan to open source? Thank you for your answer.

**Comment by cattaneod** [comment]
Hi @tqltech ,

Thank you for your interest. I am currently working on an improved version of CMRNet++ with better generalization. I plan to submit this new version for publication, and it'll be available on arxiv soon.

Regarding the code, however, it will have to wait until this new paper will be accepted for publication, which might take long time.
