### ISSUE TITLE
How can i run this project on RTX3090?

### ISSUE THREAD

**Issue by WJ1214** [catta202000/CMRNet#7]
Hi! I'm trying to run this project these days, and my GPU is RTX3090, CUDA version is 11.1. To meet the request of RTX3090 and CUDA11.1, I added 'arch=compute_80, code=sm_80' and 'arch=compute_80, code=compute_80' to nvcc_args, and changed cxx_args to ['-std=c++14']. However, I still get some error like this
![image](https://user-images.githubusercontent.com/51085092/169044056-89fa5521-d61c-492e-9fd8-11fa4585543a.png)
How can i solve this error and run build this project?

**Comment by cattaneod** [comment]
Are you sure that you are using CUDA 11.1? From the error it seems that CUDA is older than 11.
can you try to run:
`/usr/local/cuda/bin/nvcc --version`
and paste the output?

**Comment by WJ1214** [comment]
> 

sorry, I mixed up. The results of `nvcc -V`show that I'm using CUDA11.2 now. But I also tried CUDA11.1. It returns the same error.

**Comment by cattaneod** [comment]
Can you try only with `arch=compute_80, code=sm_80`, without the second argument `arch=compute_80, code=compute_80`

**Comment by WJ1214** [comment]
> Are you sure that you are using CUDA 11.1? From the error it seems that CUDA is older than 11. can you try to run: `/usr/local/cuda/bin/nvcc --version` and paste the output?

Thank you, I may know the reason why.

**Comment by WJ1214** [comment]
> Can you try only with `arch=compute_80, code=sm_80`, without the second argument `arch=compute_80, code=compute_80`

Let me try to change the CUDA version and nvcc_args, I will give you a result.

**Comment by WJ1214** [comment]
> Can you try only with `arch=compute_80, code=sm_80`, without the second argument `arch=compute_80, code=compute_80`

Hi! Now I can build project successfully, but I get another problem... It returns this error when I try to run train model script:
![image](https://user-images.githubusercontent.com/51085092/169050497-56d0e239-bad3-4a0d-9edc-b138e562c534.png)
It's weird...

**Comment by cattaneod** [comment]
Now the error is probably that you have installed pytorch with a different version of cuda than the one that you used to compile the packages.

I suggest that you create a new python environment (e.g. conda environment), install pytorch with the correct cuda version that you will use to compile the packages, and finally, before running `python setup.py install`, remove the build folder with `rm -rf build`

**Comment by WJ1214** [comment]
> 

OK, I will try it. Thank you!

**Comment by cattaneod** [comment]
And, as mentioned in https://github.com/cattaneod/CMRNet/issues/4, can you modify the file `models/CMRNet/correlation_package/correlation.py` and invert the first two lines?

**Comment by WJ1214** [comment]
> And, as mentioned in #4, can you modify the file `models/CMRNet/correlation_package/correlation.py` and invert the first two lines?

You mean that I need to `import torch` first and then `import correlation_cuda` in correlation.py?

**Comment by cattaneod** [comment]
> You mean that I need to `import torch` first and then `import correlation_cuda` in correlation.py?

Yes, exactly

**Comment by WJ1214** [comment]
> > You mean that I need to `import torch` first and then `import correlation_cuda` in correlation.py?
> 
> Yes, exactly

OKay...I will try it

**Comment by WJ1214** [comment]
It worked! Thank you very much!

**Comment by cattaneod** [comment]
Thank you for your feedback, I updated the code to run on newer versions of pytorch and with cuda 11.x
